<?php

$helper = $this->params()->fromQuery('helper','');
$log = $this->logger();

switch ($helper) {
    case 'Scenario':
        $scenario = $this->ScenarioFactory($this->params());
        echo $this->json($scenario);                
        break;
    case 'mediaRender':
        $media = $this->api()->read('media',$this->params()->fromQuery('id'))->getContent();
        echo $media->render();
    break;
}


?>



