<!-- formulaire pour ajouter une couche -->
<div class="container bg-dark text-white p-2" style="display:none" id="mdAddLayers">
    <div class="row">
        <div class="col-12">
            <div id="choixCategories">
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-between mt-2">
        <button id='btnAddLayers' class="btn btn-danger" >Ajouter</button>
    </div>
</div>
