<?php
$json = $this->params()->fromQuery('json') ? $this->params()->fromQuery('json') : $this->params()->fromPost('json', '');
if($json){
    echo $this->content;
    return ;
}

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('description', "Generator Story");

$this->headMeta()->appendName('author', "Samuel Szoniecky");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');

$this->headTitle("GenStory")->setSeparator(' · ');

$this->headScript()->appendFile($this->assetUrl('js/d3.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/d3-queue.v3.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/anime.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/bootstrap.bundle.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/amazelogo.js'));
$this->headScript()->appendFile($this->assetUrl('js/all.min.js'));//fontawesome
$this->headScript()->appendFile($this->assetUrl('js/jquery-3.6.0.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/jBox.all.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/video.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/genstory.js'));
$this->headScript()->appendFile($this->assetUrl('js/typeahead.bundle.js'));
$this->headScript()->appendFile($this->assetUrl('js/handlebars.min.js'));



$this->headLink()->prependStylesheet($this->assetUrl('css/user-bar.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/bootstrap.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/cover.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/video-js.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/jBox.all.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/genstory.css'));

//pour l'autocompletion
$this->headLink(array('rel'  => 'manifest','href' => $this->assetUrl('../manifest.json')));



$this->trigger('view.layout');

?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
<?php echo $this->htmlElement('html')->setAttribute('class', "h-100"); ?>

    <head>
        <?php echo $this->headMeta(); ?>
        <link rel="shortcut icon" href="<?php echo $this->assetUrl('img/icons/favicon.ico'); ?>" type="image/x-icon" />
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

    </head>
    <body class="d-flex h-100 text-center text-white bg-dark">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <?php echo $this->partial('genstory/header-info', ['site'=>$site]);?>
    
      <main id='mainContent' class="px-3">

        <?php 
            echo $this->content; 
        ?>            

      </main>
    
      <?php echo $this->partial('genstory/footer');?>

    </div>
    
            
      </body>
    </html>